<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6zPl3ni\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6zPl3ni/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container6zPl3ni.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container6zPl3ni\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container6zPl3ni\App_KernelProdContainer([
    'container.build_hash' => '6zPl3ni',
    'container.build_id' => 'eee18f73',
    'container.build_time' => 1743786060,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6zPl3ni');
