<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCaLn1dx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCaLn1dx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCaLn1dx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCaLn1dx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCaLn1dx\App_KernelDevDebugContainer([
    'container.build_hash' => 'CaLn1dx',
    'container.build_id' => 'dbf10f7b',
    'container.build_time' => 1744299046,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCaLn1dx');
