<?php

namespace ContainerCaLn1dx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssetMapper_Importmap_Command_ExportService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'asset_mapper.importmap.command.export' shared service.
     *
     * @return \Symfony\Component\AssetMapper\Command\ImportMapExportCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/asset-mapper/Command/ImportMapExportCommand.php';

        $container->privates['asset_mapper.importmap.command.export'] = $instance = new \Symfony\Component\AssetMapper\Command\ImportMapExportCommand(($container->privates['asset_mapper.importmap.manager'] ?? $container->load('getAssetMapper_Importmap_ManagerService')));

        $instance->setName('importmap:export');
        $instance->setDescription('Exports the importmap JSON');

        return $instance;
    }
}
