<?php

namespace ContainerCaLn1dx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLogoutSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventListener\LogoutSubscriber' shared autowired service.
     *
     * @return \App\EventListener\LogoutSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventListener/LogoutSubscriber.php';

        return $container->privates['App\\EventListener\\LogoutSubscriber'] = new \App\EventListener\LogoutSubscriber(($container->services['router'] ?? self::getRouterService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
