twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        tamila: 'wwww.tamila.cl'

when@test:
    twig:
        strict_variables: true
