<?php

namespace Container6zPl3ni;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssetMapper_Importmap_Command_ExportService extends App_KernelProdContainer
{
    /*
     * Gets the private 'asset_mapper.importmap.command.export' shared service.
     *
     * @return \Symfony\Component\AssetMapper\Command\ImportMapExportCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['asset_mapper.importmap.command.export'] = $instance = new \Symfony\Component\AssetMapper\Command\ImportMapExportCommand(($container->privates['asset_mapper.importmap.manager'] ?? $container->load('getAssetMapper_Importmap_ManagerService')));

        $instance->setName('importmap:export');
        $instance->setDescription('Exports the importmap JSON');

        return $instance;
    }
}
