<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBTyAjOA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBTyAjOA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBTyAjOA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBTyAjOA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBTyAjOA\App_KernelDevDebugContainer([
    'container.build_hash' => 'BTyAjOA',
    'container.build_id' => '6ec0847a',
    'container.build_time' => 1744059309,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBTyAjOA');
